image:
  repository: 975324004664.dkr.ecr.ap-northeast-2.amazonaws.com/passorder-api
  tag: 199

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"